### ISSUE TITLE
Still supporting IDE debugging?

### ISSUE THREAD

**Issue by joshuanathanson** [astashov/debugger-xml#19]
Hello, I am having some issues when trying to set up debugger-xml for Intellij 13.

The first error I get is "require: can't load such file debugger/xml"

I see in rdebug-ide that it is trying to require debugger/xml, but there is no file by that name.  Perhaps it should be "debugger_xml" instead?

If I change it to debugger_xml, I then get the error in debugger_xml.rb, line 2, "uninitialised constant DEBUGGER_TYPE".  When I search the gem for that text, it is not used anywhere else.  

That was as far as I got.  Please advise as to next steps.

**Comment by os97673** [comment]
It looks like debugger-xml >= 0.4.0 doesn't work with IDE :( use 0.3.3 instead.

**Comment by joshuanathanson** [comment]
Hello,

Thank you for getting back to me.  OK, using 0.3.3 I got debugging up and running in my IDE.  However, when the code hits a breakpoint, I get the following error:

```
yld: lazy symbol binding failed: Symbol not found: _rb_vm_get_sourceline
  Referenced from: xxx/.rvm/gems/ruby-2.1.1@peat/extensions/x86_64-darwin-12/2.1.0-static/debugger-1.6.8/ruby_debug.bundle
  Expected in: flat namespace
```

I did a google search for that error and found a link to an issue in your vim-ruby-debugger Github repo, but I couldn't find if there was a solution to that issue yet.  Is there anything else I can try?

**Comment by os97673** [comment]
0.3.3 is using debugger which doesn't not support ruby > 2.0 :(
As far as I can see (#17) @astashov is working on adding support for byebug which works for ruby 2.0 and later, but it is still in progress :(

**Comment by astashov** [comment]
Hey guys, really sorry for delay and silence, was super busy.
I gonna try to finish byebug support this week. Stay tuned :)

**Comment by os97673** [comment]
0.5.0.pre1 should work ok with debugger and works somehow with byebug ;)
At least you can add this version to your Gemfile and it will install correct dependency.
Thus I'm closing the ticket, see #17 to get notified when byebug support will be completed.
