### ISSUE TITLE
Can't start byebug 5.0.0 with debugger-xml 0.5.0.pre1/2 

### ISSUE THREAD

**Issue by akutarba** [astashov/debugger-xml#20]
Steps to Reproduce:
1. Use any application with byebug 5.0.0 and debugger-xml  0.5.0.pre2 in Gemfile. 
2. Run in the Terminal the command: rdebug-xml --debug bin/rails server  -p 3000.
3. Get the message that: 
Fast Debugger (debugger-xml 0.5.0.pre2, byebug 5.0.0) listens on 127.0.0.1:3000
4. Try to browse application on the http://localhost:3000

Get the error:

Read command: GET / HTTP/1.1
Going to print: INTERNAL ERROR!!! Can't find part path 'base.errors.no_suspended_thread'
Going to print:         /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/byebug-5.0.0/lib/byebug/printers/base.rb:25:in `locate'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/byebug/printers/xml.rb:81:in `print_content'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/byebug/printers/xml.rb:67:in `block in print_error'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/byebug/printers/xml.rb:67:in `print_error'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/byebug/printers/xml.rb:11:in `print'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/debugger_xml/byebug_proxy.rb:38:in `print'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/debugger_xml/ide/control_command_processor.rb:42:in `process_context_commands'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/debugger_xml/ide/control_command_processor.rb:27:in `block in process_command'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/debugger_xml/ide/control_command_processor.rb:23:in `catch'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/debugger_xml/ide/control_command_processor.rb:23:in `process_command'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/debugger_xml/ide/control_command_processor.rb:36:in `block in process_input'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/debugger_xml/ide/control_command_processor.rb:35:in `each'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/debugger_xml/ide/control_command_processor.rb:35:in `process_input'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/debugger_xml/ide/control_command_processor.rb:12:in `process_commands'
        /Users/jetbrains/.rvm/gems/ruby-2.2.0@rails4/gems/debugger-xml-0.5.0.pre2/lib/debugger_xml.rb:29:in `block in start_remote_ide'

**Comment by os97673** [comment]
Cannot reproduce :(  It looks like we are missing some important piece of information :(
